site_name: 森韬L240自主无人机开发文档
theme:
  name: material

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      toc_depth: 3 #目录深度，默认6，0则隐藏
      title: On this page  #默认值，自动获取
      permalink: true   #每个标题的末尾添加段落符号锚链接，默认false
      permalink: ⚓︎  #每个标题的末尾添加自定义符号锚链接
      permalink_title: Anchor link to this section for reference #在悬停时显示并由屏幕阅读器阅读的锚链接的标题
      slugify: !!python/name:pymdownx.slugs.uslugify  #自定义 slug
      slugify: !!python/name:pymdownx.slugs.uslugify_cased   #自定义 slug

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

